---
include:

# Hillside 46
#   Comment out below if you do not have this board, to save build time
  - board: nice_nano_v2
    shield: hillside46_left
  - board: nice_nano_v2
    shield: hillside46_right
  - board: nice_nano_v2
    shield: settings_reset